### ISSUE TITLE
Image 'hfs_x64.efi' is not an image.

### ISSUE THREAD

**Issue by ElvishJerricco** [pbatard/EfiFs#12]
Running OVMF in qemu, going to the UEFI Shell, and entering `load hfs_x64.efi` yields `Image 'hfs_x64.efi' is not an image.` I'm not sure whether it's OVMF or EfiFs at fault, but the other EfiFs drivers that I've tried have worked so I'm assuming it's EfiFs. Both OVMF and EfiFs were built with both their latest releases and their latest commits on `master`.

Are there tools I can use to try and debug this?

**Comment by pbatard** [comment]
It's your OVMF. Here's what I get with the last official OVMF binary from https://sourceforge.net/projects/edk2/files/OVMF/ against a gnu-efi Debian 9.6 `hfs_x64.efi`:

![image1](https://user-images.githubusercontent.com/1206968/49022002-c1dc7980-f18b-11e8-95ce-d868fec4225d.png)

**Comment by ElvishJerricco** [comment]
@pbatard Not sure what I did, but it's loading now. FWIW, the README on that site says:

```
The Latest releases are now hosted on Github: https://github.com/tianocore
```

Though I can't find binary releases there

**Comment by pbatard** [comment]
Yes, the source had moved, but the last official OVMF binaries are still on SF, and, where possible, I prefer to validate against official binaries as this reduces the headaches (which you have experienced) of introducing one's own issues through one's build process. With EfiFs being a side project for which I can devote only __very limited time__ compared to my other projects, I have exactly zero incentive to figure out the many ways in which things can break from trying to use the very latest of everything.
