### ISSUE TITLE
[Enhancement] Encryption driver for LUKs/dm-crypt

### ISSUE THREAD

**Issue by gadgethm** [pbatard/EfiFs#28]
Any plans to add the ability to decrypt encrypted /boot partitions?  It seems like full disk encryption for linux installations is becoming more common, and this would allow for tighter control of one's boot partition and/or bootloader.

Thoughts?

**Comment by pbatard** [comment]
> Any plans to add the ability to decrypt encrypted /boot partitions?

None.

>  It seems like full disk encryption for linux installations is becoming more common, and this would allow for tighter control of one's boot partition and/or bootloader.

That's great. If someone wants to send a patch, I'll be happy to consider it for inclusion. But I am personally way too busy with other stuff to want to look in adding decryption support to EfiFs, sorry.
