### ISSUE TITLE
Executing EFI Binaries On Newly Loaded Filesystems

### ISSUE THREAD

**Issue by 0x0D15** [pbatard/EfiFs#30]
Had a quick question/issue about the possibility of executing efi binaries on newly loaded filesystems such as btrfs or ext4. I see that efifs is specifically denoted as read-only but was wondering if there is any way to also execute efi binaries that can be read. Thanks for any help.

**Comment by pbatard** [comment]
Those are drivers, so once the driver is loaded, you can execute whatever executable you can read from the corresponding file system.

For an example of a bootloader that loads an EfiFs driver (in this case the NTFS one) and then runs an EFI executable residing on the NTFS volume, which the EfiFs driver just granted access to, see https://github.com/pbatard/uefi-ntfs.
