### ISSUE TITLE
Can't see Ext4 partition (I'm using VirtualBox)

### ISSUE THREAD

**Issue by q2dg** [pbatard/EfiFs#34]
Hello.

I've downloaded "ext2_x64.efi" fle from your web but, after having loaded, when I remap filesystem in VirtualBox's UEFI Shell, nothing happens: my Ext4 partition continues just recognized as "blk", not "fs".

I don't know if it is a problem of your driver or it's a VirutualBox UEFI's implementation's one but I think it was worthy to open an issue about this, in order to debug the problem (hope I'm not mistaken).

Thanks a lot for your splendid project.

**Comment by pbatard** [comment]
I run regular tests (using QEMU) for the ext4 driver, and I am not aware of any issue. This is a test I just re-ran with the exact `ext2_x64.efi` driver that's published on the web site:

![Image2](https://user-images.githubusercontent.com/1206968/134336919-e4a2439f-e0af-48eb-81a6-b8c7acf1b5e4.png)

IIRC, it's not the first time people report issues with VirtualBox, and I'm afraid I have no time (or interest) for debugging what happens there when the driver works fine with QEMU or real systems. You will have to investigate this problem yourself, sorry.

**Comment by q2dg** [comment]
I understand, no problem!
Thanks!
