### ISSUE TITLE
Possible to go backwards? Extract EFI from FFS??

### ISSUE THREAD

**Issue by davidm71** [pbatard/EfiFs#41]

**Comment by pbatard** [comment]
Probably. You most likely want to use `GenSec`/`GenFfs` if they have a reverse option. I'm afraid I'm not going to help you there, but the whole thing is Open Source, so if **you** really want to do it, you most certainly can (but please don't ask somebody else to do that for you). Also, you may want to have a look [here](https://github.com/pbatard/ffs).
