### ISSUE TITLE
Curious file read problem

### ISSUE THREAD

**Issue by 593749519** [pbatard/EfiFs#9]
I tried to write a efi application to read large files(more than 10G), when read file from offset 4155201536, the ntfs driver hangs and the exfat driver return device error。This offset does not exceeded 4G, so I tried to read from 4G above or just before EOF, it's OK. Yes, it's really strange.

**Comment by 593749519** [comment]
Sorry, my fault. the original ntfs driver in UEFI firmware is buggy. The current version I compiled works fine.

**Comment by pbatard** [comment]
Okay. I will close this issue then.
